### PR TITLE
Don't package auto-generated docs

### PR DESCRIPTION
**Pull request by lgeiger**

### CODE REVIEW

**Comment by rgbkrk** [comment]
Oh _our_ packages were including them! Thank you @lgeiger.

**Comment by rgbkrk** [comment]
Added you on npm for commutable.

**Comment by lgeiger** [comment]
> Oh our packages were including them!

Yes the ones which have `.npmignore` files do. Otherwise the `.gitignore` handles everything correctly.

**Comment by lgeiger** [comment]
`commutable` doesn't need a patch. They are no docs included in the latest version.

**Pull request merged**
